Region: ${AWS_REGION_NAME}
Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.2xlarge
  Networking:
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  LocalStorage:
    RootVolume:
      Size: 1024
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: trainium
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
          EphemeralVolume:
            MountDir: /local_storage
      ComputeResources:
        - Efa:
            Enabled: true
          InstanceType: trn1.32xlarge
          MaxCount: 8
          MinCount: 0
          Name: trn1-32xlarge
      Networking:
        SubnetIds:
          - ${SUBNET_ID}
        PlacementGroup:
          Enabled: true
SharedStorage:
- EfsSettings:
    ProvisionedThroughput: 1024
    ThroughputMode: provisioned
  MountDir: /efs
  Name: neuron
  StorageType: Efs