Region: ${AWS_REGION_NAME}
Image:
  Os: alinux2
HeadNode:
  InstanceType: c5.2xlarge
  CustomActions:
    OnNodeConfigured:
      Args:
        - 00.install.neuron.headnode.sh
      Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
  Networking:
    SubnetId: ${HN_SUBNET_ID}
  Ssh:
    KeyName: ${KEY_PAIR}
  LocalStorage:
    RootVolume:
      Size: 1024
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: trainium
      CapacityType: ONDEMAND
      ComputeSettings:
        LocalStorage:
          RootVolume:
            Size: 1024
          EphemeralVolume:
            MountDir: /local_storage
      ComputeResources:
        - Efa:
            Enabled: true
          InstanceType: trn1.32xlarge
          MaxCount: 8
          MinCount: 8
          Name: trn1-32xlarge
      CustomActions:
        OnNodeConfigured:
          Args:
            - 00.install.neuron.trainium.sh
          Script: s3://${S3_BUCKET}/1click-hpc/scripts/post.install.sh
      Networking:
        SubnetIds:
          - ${SUBNET_ID}
        PlacementGroup:
          Enabled: true
SharedStorage:
${FSX}
